---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
#Only install these packages one time! Then either delete this chunk or comment it out!
#install.packages("devtools")
#devtools::install_github("ucl-cssb/flopr")
```

```{r load and other packages, include = FALSE}

# Packages To Install -----------------------------------------------------
source("../Functions/Load_Packages.R")
```

```{r load thematic elements}
# thematic elements -----------------------------------------------------
source("../Functions/SKS_Personal_Theme.R")
```

## Loading Data

```{r}

#using the flopr package to wrangle TECAN Spark data. See flopr on github for more info!
#' @param data_csv needs to be the raw TECAN data in CSV form!
#' @param layout_csv needs to be filled in according to the example layout.
#'    you can add as many columns as you want BUT THE LAST COLUMN MUST BE named 'well' and have the position for each well such as 'A1'

plate1 <- drop_na(flopr::spark_parse(data_csv = "../Data/Albert_Data.csv",
                                     layout_csv = "../Data/Albert_Metadata.csv",
                                     timeseries = TRUE))

#Change time if necessary! I am changing from seconds to hours!
plate1 %<>%
  mutate(across(time, ~.x / 3600)) %>%
  mutate(across(Plasmid, str_replace, 'del', '')) %>%
  modify_if(is.character, as.factor) %>% 
  modify_at(c("Replicate"), as.factor)



#this is if you need to use multiple plates for your analysis!

#readydata <- plate1 %>%
 # full_join(plate2) %>%
  #Wrangling data to make plots more easy to read.
  #mutate(across(Plasmid, str_replace, 'pLW003', 'ev')) %>%
  #mutate(across(Plasmid, str_replace, 'pLW002', '+SIR')) %>%
  #mutate(Variant = Plasmid)
  

#rm(plate1); rm(plate2)
```

## Max and Min OD Graphs

### Quick visualization of data

```{r}
#Filtering just positive controls for easy example
PosCtrl <- plate1 %>%
  filter(Plasmid == "pJA018")
  
  
```

```{r fig.height = 6, fig.width = 8}
#example of plotting raw data! I am only going to plot positive controls for this example!

 plate1 %>%
  ggplot(aes(x = time, y = OD562, color = as.factor(Replicate), shape = Plasmid)) +
  geom_point() +
  labs(title = "Positive Control") + 
  Theme

```

## Nesting Data

```{r}
#In this case it's best to filter the data less than three hours because the max value the plate reader can measure is an OD of 4 for OD_562. 
#IF YOU HAVE NEGATIVE CONTROLS YOU WILL NOT BE ABLE TO FIT GROWTH CURVES TO THEM

plate1 %<>%
  filter(OD562 <= 3.5) %>%
  group_by(Plasmid, Replicate) %>%
  mutate(OD562 = OD562 - min(OD562) + .0001)
```

```{r}
 plate1 %>%
  ggplot(aes(x = time, y = OD562, color = as.factor(Replicate), shape = Plasmid)) +
  geom_point() +
  labs(title = "Positive Control shifted to ~0", x = "Time (Hr)", y = "") +
  scale_x_continuous(limits=c(0, 3)) + 
  scale_y_continuous(limits=c(0, 3)) +
  ggthemes::scale_color_colorblind() +
  Theme
```


```{r nest data}
#' @concept This is creating a nested data frame. The main difference between a nested data frame and grouped data frame is that for a grouped data frame, each row is an observation. For a nested data frame each row is a group of observations!

#This will allow us to easily apply function/models across all the data available. 
#Using Tidymodels we can then easily organize the coefficients for our different models!

#the across function allows for selecting specific columns! I want the default time column and I want any column that has the word OD in it in case someone uses multiple ODs for flourescent proteins! 

#THIS WILL ONLY WORK IF YOUR OPTICAL DENSITY CHANNELS HAVE THE WORD OD IN THEM!

plate1 %<>%
  select(-c(well, row, column)) %>%
  group_by(across(-c(time, contains("OD")))) %>%
  nest()
  
```

## Fitting Positive Controls

### Fitting Controls

```{r Data Modeling and Summary Statistics}

source("../Functions/Exponential_Fit.R")

#fitting model and collecting coefficients

 plate1 %>%
   filter(Strain != "Blank" & Plasmid != "pIC004") %>%
  #apply Exponential model to the data
  mutate(model = map(data, Exponential_Fit)) %>%
  #Create summary of coefficients
  mutate(summary = map(model, tidy)) %>%
  #Get residuals for model that can be plotted on top in a ggplot object
  mutate(augment = map(model, augment)) %>%
  #Using Glance to get an idea of model fit 
  mutate(model.fit = map(model, glance)) -> output

```

```{r plotting 4-HT controls, fig.height= 6, fig.width= 10}
 output %>%
  unnest(augment) %>%
  ggplot(aes(x = time, y = OD562)) + 
  geom_point(size = 2) + 
  geom_line(aes(y = .fitted, group = Replicate), color = "blue", size = 1) +
  labs(y = 'Absorbance ('~OD[562]~')', x = "Timepoint (Hr)", title = "Exponential Fit") +
  scale_x_continuous(limits=c(0, 3)) + 
  scale_y_continuous(limits=c(0, 3)) +
  facet_wrap(~Plasmid) +
Theme

```

```{r}
 output %>%
  unnest(augment) %>%
  filter(Plasmid == "del35-114") %>%
  ggplot(aes(x = time, y = .resid)) + 
  geom_point(size = 1.5) + 
  labs(y = "Residual" , x = "Timepoint (Hr)", title = "Residuals") +
  scale_x_continuous(limits=c(0, 3)) + 
  scale_y_continuous(limits=c(-.5, .5)) +
  facet_wrap(~Replicate) +
Theme
```

```{r unnesting for boxplotting of 4-HT controls coefficients}

output %<>%
  unnest(summary) %>%
  pivot_wider(names_from = term, values_from = c(estimate, std.error, statistic,p.value))

```

## Investigating Difference in Growth Rate Between Positive Control Conditions

```{r}
#Creating a boxplot to compare the knockouts

output %>%
ggplot(aes(x= reorder(Plasmid, estimate_r, FUN = median), y = estimate_r)) + 
    geom_boxplot() + 
  labs(x = "Domain Insertion", y = "Rate Estimate") +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  scale_y_continuous(limits=c(0, 7)) +
  Theme
```

```{r}
#Seems to be a difference in maximum growth rate! Based on my T-test!
#Therefore I need to proceed with caution and compare cultures to their respective positive controls.
PosCtrl %>%
  infer::t_test(formula = estimate_mu ~ Inducer,
              order = c("DMSO", "4-HT"),
              alternative = "two-sided")
```

## Calculating Starting Parameters for Conditions

```{r}
#I calculated the means for the positive controls by condition. You can use these parameters for the Zwietering_A.fit model if you want to threshold the max OD for your experimental trials!
 
starting_parameters <- PosCtrl %>%
  group_by(Plasmid,Inducer) %>%
  summarize(avg.estimate_A = mean(estimate_A),
            avg.estimate_mu = mean(estimate_mu),
            avg.estimate_lambda = mean(estimate_lambda),)

starting_parameters

HT_param <- starting_parameters %>%
  slice(1) 
 
DMSO_param <- starting_parameters %>%
  slice(2)

```


