---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
#Only install these packages one time! Then either delete this chunk or comment it out!
install.packages("devtools")
devtools::install_github("ucl-cssb/flopr")
```

```{r load and other packages}

# Packages To Install -----------------------------------------------------
source("../Functions/Load_Packages.R")
```

```{r load thematic elements}
# thematic elements -----------------------------------------------------
source("../Functions/SKS_Personal_Theme.R")
```

## Loading Data

```{r}

#using the flopr package to wrangle TECAN Spark data. See flopr on github for more info!
#' @param data_csv needs to be the raw TECAN data in CSV form!
#' @param layout_csv needs to be filled in according to the example layout.
#'    you can add as many columns as you want BUT THE LAST COLUMN MUST BE named 'well' and have the position for each well such as 'A1'

plate1 <- drop_na(flopr::spark_parse(data_csv = "../Data/Example_Data.csv",
                                     layout_csv = "../Data/Metadata.csv",
                                     timeseries = TRUE))

#Change time if necessary! I am changing from seconds to hours!
plate1 %<>%
  mutate(across(time, ~.x / 3600))



#this is if you need to use multiple plates for your analysis!

#readydata <- plate1 %>%
 # full_join(plate2) %>%
  #Wrangling data to make plots more easy to read.
  #mutate(across(Plasmid, str_replace, 'pLW003', 'ev')) %>%
  #mutate(across(Plasmid, str_replace, 'pLW002', '+SIR')) %>%
  #mutate(Variant = Plasmid)
  

#rm(plate1); rm(plate2)
```

## Max and Min OD Graphs

### Quick visualization of data

```{r}
#Filtering just positive controls for easy example
PosCtrl <- plate1 %<>%
  filter(Type == "PosCtrl") %>%
  
  
```

```{r fig.height = 6, fig.width = 8}
#example of plotting raw data! I am only going to plot positive controls for this example!

p <- PosCtrl %>%
  filter(Inducer == "4-HT") %>%
  ggplot(aes(x = time, y = OD600, color = as.factor(Replicate))) +
  geom_point() +
  labs(title = "4-HT condition") +
  ggthemes::scale_color_colorblind() +
  Theme

q <- PosCtrl %>%
  filter(Inducer == "DMSO") %>%
  ggplot(aes(x = time, y = OD600, color = as.factor(Replicate))) +
  geom_point() +
  labs(title = "DMSO condition") +
  ggthemes::scale_color_colorblind() +
  Theme

ggarrange(p,q, common.legend = TRUE)

```

## Creating Max OD boxplot

```{r}
#Calculating the min and maximum OD for all positive controls
PosCtrl %>% 
  group_by(Replicate, Inducer, Plate) %>%
  slice_max(OD600, n = 1) -> pos_max_OD

#Finding the average time of max OD. This is what I will filter teh data by before I apply the model. Remember no death phase can be included in the model!
pos_max_OD %>%
  pull(time) %>%
  mean() -> time_max

#Now I will find the closest measured value from all the replicates using the Closest Function from the DescTools package!

nearest_time <- round(Closest(PosCtrl$time, time_max ),2)

#Finding max OD based on when the positive controls hit their maximum.
PosCtrl %>%
  select(!c("well", "row", "column")) %>%
  group_by(Plasmid, Replicate,Inducer, Plate, Type) %>%
  mutate(across(time, round, 2)) %>%
  filter(time == nearest_time[[1]]) -> max_OD


```

```{r}
#Calculating fold change between different conditions (optional)
max_OD %>%
  pivot_wider(names_from = Inducer, values_from = c(time, OD600)) %>%
  mutate(OD_fold = (`OD600_4-HT` - OD600_DMSO)/OD600_DMSO) %>%
  group_by(Plasmid) %>%
  summarize(mean_OD_fold = round(mean(OD_fold),3)) %>%
  select(Plasmid,mean_OD_fold) %>%
  ungroup() -> fold_changes

max_OD %<>% 
  left_join(fold_changes)

```

```{r}
 max_OD %>%
  ggplot(aes(x = Plasmid, y = OD600, fill = Inducer)) +
  geom_boxplot(outlier.shape = NA) +
  geom_text(aes(x = Plasmid, y = 1.9, label = paste('Delta', "==", mean_OD_fold)), parse = T, size = 5, check_overlap = T) +
  geom_point(width = .4, position = position_dodge(width = .75), size = .75) +
  geom_hline(yintercept = .05, linetype = 2, color = "black") +
  geom_vline(xintercept = 1.5, color = "#C0C0C0", size = 1) +
  scale_y_continuous(limits=c(0, 2), n.breaks = 10) +
  scale_fill_manual(values = c("#A9A9A9", "white")) +
  labs(x = "Controls", y = "") +
  coord_flip() +
  Theme + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_blank(),
        axis.ticks.x= element_blank(),
        axis.text.y = element_text(size = 8))

#ggsave("Images/max_OD.jpg", width = 180, height = 185, units = c("mm"))
```

```{r}
#clearing memory for optimal computer function
rm(p); rm(q); rm(max_OD)
```

## Nesting Data

```{r}
#For model fitting to work you need to exclude the death phase. The model cannot account for the drop in optical density following stationary.

#Therefore, I will filter the data before 15 hours.

#IF YOU HAVE NEGATIVE CONTROLS YOU WILL NOT BE ABLE TO FIT GROWTH CURVES TO THEM

plate1 %<>%
  filter(time < time_max)
```


```{r}
#' @concept This is creating a nested data frame. The main difference between a nested data frame and grouped data frame is that for a grouped data frame, each row is an observation. For a nested data frame each row is a group of observations!

#This will allow us to easily apply function/models across all the data available. 
#Using Tidymodels we can then easily organize the coefficients for our different models!

#the across function allows for selecting specific columns! I want the default time column and I want any column that has the word OD in it in case someone uses multiple ODs for flourescent proteins! 

#THIS WILL ONLY WORK IF YOUR OPTICAL DENSITY CHANNELS HAVE THE WORD OD IN THEM!

PosCtrl %<>%
  select(-c(well, row, column)) %>%
  group_by(across(-c(time, contains("OD")))) %>%
  nest()
  
```

## Fitting Positive Controls

### Fitting 4-HT Positive Controls

```{r Data Modelling and Summary Statistics 4-HT Positive Controls}

source("../Functions/Zwietering_Fitting_Functions.R")

#fitting model and collecting coefficients

 PosCtrl %<>%
  #apply Zwietering model to the data
  mutate(model = map(data, Zwietering.fit)) %>%
  #Create summary of coefficients
  mutate(summary = map(model, tidy)) %>%
  #Get residuals for model that can be plotted on top in a ggplot object
  mutate(augment = map(model, augment)) %>%
  #Using Glance to get an idea of model fit 
  mutate(model.fit = map(model, glance)) 

```

```{r plotting 4-HT controls, fig.height= 6, fig.width= 10}
PosCtrl %>%
  unnest(augment) %>%
  ggplot(aes(x = time, y = OD600)) + 
  geom_point(size = 1.5) + 
  geom_line(aes(y = .fitted), color = "blue", size = 1.25) +
  labs(y = 'Absorbance ('~OD[600]~')', x = "Timepoint (Hr)", title = "4-HT Positive Controls") +
  scale_x_continuous(limits=c(0, 17)) + 
  scale_y_continuous(limits=c(0, 1.8)) +
  facet_wrap(Plate ~ Replicate) +
Theme

```

```{r unnesting for boxplotting of 4-HT controls coefficients}

PosCtrl %<>%
  unnest(summary) %>%
  pivot_wider(names_from = term, values_from = c(estimate, std.error, statistic,p.value))

```

## Investigating Difference in Growth Rate Between Positive Control Conditions

```{r}
#Creating a boxplot to compare the positive controls in different media conditions.
#Do you notice anything...?
ggbetweenstats(
  data = PosCtrl,
  x = Inducer,
  y = estimate_mu
)
```

```{r}
#Seems to be a difference in maximum growth rate! Based on my T-test!
#Therefore I need to proceed with caution and compare cultures to their respective positive controls.
PosCtrl %>%
  infer::t_test(formula = estimate_mu ~ Inducer,
              order = c("DMSO", "4-HT"),
              alternative = "two-sided")
```

## Calculating Starting Parameters for Conditions

```{r}
#I calculated the means for the positive controls by condition. You can use these parameters for the Zwietering_A.fit model if you want to threshold the max OD for your experimental trials!
 
starting_parameters <- PosCtrl %>%
  group_by(Plasmid,Inducer) %>%
  summarize(avg.estimate_A = mean(estimate_A),
            avg.estimate_mu = mean(estimate_mu),
            avg.estimate_lambda = mean(estimate_lambda),)

starting_parameters

HT_param <- starting_parameters %>%
  slice(1) 
 
DMSO_param <- starting_parameters %>%
  slice(2)

```

## Analyzing Variant Model Coefficients

```{r combining growth variant data frames, eval=FALSE, include=FALSE}

#this code chunk could be useful for comparing coefficients between groups! I currently have it not running but you can remove the eval=FALSE to run it!
fitted_growth_variants <- positive_controls %>%
  select(!c(estimate_A, std.error_A, statistic_A, p.value_A)) %>%
  full_join(Growth_4HT_Variants) %>%
  full_join(Growth_DMSO_Variants)

fitted_growth_variants %<>%
  select(!model) %>%
  modify_if(is.character, as.factor) %>%
ungroup() %>%
  mutate(Plasmid = Plasmid %>%
           fct_relevel("+SIR")
         )

rm(positive_controls); rm(Growth_4HT_Variants); rm(Growth_DMSO)
```

